//
// Generated by JTB 1.2.2
//

package xtc.lang.javacc.syntaxtree;

/**
 * Grammar production.
 * <pre>
 * f0 -> ConditionalExpression()
 * f1 -> [ AssignmentOperator() Expression() ]
 * </pre>
 */
public class Expression implements Node {
   public ConditionalExpression f0;
   public NodeOptional f1;

   public Expression(ConditionalExpression n0, NodeOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(xtc.lang.javacc.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(xtc.lang.javacc.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

