//
// Generated by JTB 1.2.2
//

package xtc.lang.javacc.syntaxtree;

/**
 * Grammar production.
 * <pre>
 * f0 -> &lt;INTEGER_LITERAL&gt;
 *       | &lt;FLOATING_POINT_LITERAL&gt;
 *       | &lt;CHARACTER_LITERAL&gt;
 *       | &lt;STRING_LITERAL&gt;
 *       | BooleanLiteral()
 *       | NullLiteral()
 * </pre>
 */
public class Literal implements Node {
   public NodeChoice f0;

   public Literal(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(xtc.lang.javacc.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(xtc.lang.javacc.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

