//
// Generated by JTB 1.2.2
//

package xtc.lang.javacc.syntaxtree;

/**
 * Grammar production.
 * <pre>
 * f0 -> &lt;IDENTIFIER&gt;
 * f1 -> FormalParameters()
 * f2 -> ( "[" "]" )*
 * </pre>
 */
public class MethodDeclarator implements Node {
   public NodeToken f0;
   public FormalParameters f1;
   public NodeListOptional f2;

   public MethodDeclarator(NodeToken n0, FormalParameters n1, NodeListOptional n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public void accept(xtc.lang.javacc.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(xtc.lang.javacc.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

