//
// Generated by JTB 1.2.2
//

package xtc.lang.javacc.syntaxtree;

import java.util.*;

/**
 * Represents an optional grammar list, e&#46;g&#46; ( A )*.
 */
@SuppressWarnings("unchecked")
public class NodeListOptional implements NodeListInterface {
   public NodeListOptional() {
      nodes = new Vector();
   }

   public NodeListOptional(Node firstNode) {
      nodes = new Vector();
      addNode(firstNode);
   }

   public void addNode(Node n) {
      nodes.addElement(n);
   }

   public Enumeration elements() { return nodes.elements(); }
   public Node elementAt(int i)  { return (Node)nodes.elementAt(i); }
   public int size()             { return nodes.size(); }
   public boolean present()      { return nodes.size() != 0; }
   public void accept(xtc.lang.javacc.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(xtc.lang.javacc.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }

   public Vector nodes;
}

