//
// Generated by JTB 1.2.2
//

package xtc.lang.javacc.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(xtc.lang.javacc.visitor.Visitor v);
   public Object accept(xtc.lang.javacc.visitor.ObjectVisitor v, Object argu);

}

