//
// Generated by JTB 1.2.2
//

package xtc.lang.javacc.syntaxtree;

/**
 * Represents a grammar choice, e&#46;g&#46; ( A | B ).
 */
public class NodeChoice implements Node {
   public NodeChoice(Node node) {
      this(node, -1);
   }

   public NodeChoice(Node node, int whichChoice) {
      choice = node;
      which = whichChoice;
   }

   public void accept(xtc.lang.javacc.visitor.Visitor v) {
      choice.accept(v);
   }
   public Object accept(xtc.lang.javacc.visitor.ObjectVisitor v, Object argu) {
      return choice.accept(v,argu);
   }

   public Node choice;
   public int which;
}

