//
// Generated by JTB 1.2.2
//

package xtc.lang.javacc.syntaxtree;

/**
 * Grammar production.
 * <pre>
 * f0 -> "null"
 * </pre>
 */
public class NullLiteral implements Node {
   public NodeToken f0;

   public NullLiteral(NodeToken n0) {
      f0 = n0;
   }

   public NullLiteral() {
      f0 = new NodeToken("null");
   }

   public void accept(xtc.lang.javacc.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(xtc.lang.javacc.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

