//
// Generated by JTB 1.2.2
//

package xtc.lang.javacc.syntaxtree;

/**
 * Grammar production.
 * <pre>
 * f0 -> "package"
 * f1 -> Name()
 * f2 -> ";"
 * </pre>
 */
public class PackageDeclaration implements Node {
   public NodeToken f0;
   public Name f1;
   public NodeToken f2;

   public PackageDeclaration(NodeToken n0, Name n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public PackageDeclaration(Name n0) {
      f0 = new NodeToken("package");
      f1 = n0;
      f2 = new NodeToken(";");
   }

   public void accept(xtc.lang.javacc.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(xtc.lang.javacc.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

