//
// Generated by JTB 1.2.2
//

package xtc.lang.javacc.syntaxtree;

/**
 * Grammar production.
 * <pre>
 * f0 -> PreIncrementExpression()
 *       | PreDecrementExpression()
 *       | PrimaryExpression() [ "++" | "--" | AssignmentOperator() Expression() ]
 * </pre>
 */
public class StatementExpression implements Node {
   public NodeChoice f0;

   public StatementExpression(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(xtc.lang.javacc.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(xtc.lang.javacc.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

